name: mw
description: "MW Chat – modern private messaging app. Copyright ©2025 Mousa Abu Hilal."
publish_to: 'none'

version: 1.0.3+21

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_app_check: ^0.4.1+2
  image_picker: ^1.2.1
  path: ^1.9.1
  file_picker: ^10.3.7
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  vibration: ^3.1.4
  cached_network_image: ^3.4.0
  transparent_image: ^2.0.1
  url_launcher: ^6.3.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  video_player: ^2.8.1
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4
  image: ^4.2.0
  path_provider: ^2.1.0
  firebase_database: ^12.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App Icon generator
  flutter_launcher_icons: ^0.14.4

  # Splash screen generator
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  # Needed so Flutter generates app_localizations.dart
  generate: true

  assets:
    - assets/logo/mw_mark.png
    - assets/logo/mw_mark_transparent.png
    - assets/images/mw_bg.png
    - assets/images/bear.png
    - assets/images/smurf.png
    - assets/typing/bear_keyboard.png
    - assets/typing/smurf_keyboard.png
    - assets/emojis/

  # =========================
  # FONT FAMILIES
  # =========================
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700

# =========================
# APP ICON CONFIGURATION
# =========================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/mw_mark.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/logo/mw_mark.png"

# =========================
# SPLASH SCREEN CONFIGURATION
# =========================
flutter_native_splash:
  color: "#0E0E0E"
  image: assets/logo/mw_mark_transparent.png
  android: true
  ios: true
  web: true
  fullscreen: true

  image_dark: assets/logo/mw_mark_transparent.png

  android_12:
    image: assets/logo/mw_mark_transparent.png
    icon_background_color: "#0E0E0E"
